// front/src/pages/auth-page/auth-page.component.ts
import { Component } from '@angular/core';
import { ButtonComponent, InputComponent } from '../../ui';

@Component({
  selector: 'app-auth-page',
  standalone: true,
  imports: [ButtonComponent, InputComponent],
  templateUrl: './auth-page.component.html',
  styleUrl: './auth-page.component.scss'
})
export class AuthPageComponent {

}

<div class="auth-page-wrapper">
    <div class="auth-page">
        <p class="auth-title">Sosala.Tasks</p>
        <app-input [placeholder]="'email'"></app-input>
        <app-input [placeholder]="'password'"></app-input>
        <app-button [title]="'sign in'"></app-button>
    </div>
</div>

// front/src/pages/auth-page/auth-page.tsx
import { useState } from 'react';
import { Button, Modal, Input } from '../../ui';
import styles from './auth-page.module.scss';

export function AuthPage() {

    const [isOpen, setIsOpen] = useState(true);

    return (
        <Modal isOpen={isOpen} onClose={() => {setIsOpen(prev => !prev)}}>
            <div className={styles['auth-block']}>
                <p className={styles['auth-title']}>Sosala.Tasks</p>
                <div className={styles['auth-creds']}>
                    <Input placeholder='email'/>
                    <Input placeholder='passwaord'/>
                </div>
                <Button onClick={() => {}}>Login</Button>
            </div>
        </Modal>
    )   
}
